# Generated by Django 2.2.19 on 2022-05-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220526_1250'),
        ('posts', '0003_auto_20220525_2333'),
    ]

    operations = [
    ]
